custom_admin/urls.py
from django.urls import path

from newsfeed.views import profile
from . import views

app_name = 'custom_admin'

urlpatterns = [
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('users/', views.users, name='users'),
    path('delete_user/<pk>/', views.delete_user, name='delete_user'),
    path('messages/', views.contact_messages, name='messages'),
    path('products/', views.products, name='products'),
    path('delete_product/<pk>/', views.delete_product, name='delete_product'),
    path('listing_reports/', views.listing_reports, name='listing_reports'),
    path('user_reports/', views.user_reports, name='user_reports'),
    path('delete_listing_report/<pk>/', views.delete_listing_report, name='delete_listing_report'),
    path('delete_message/<pk>/', views.delete_message, name='delete_message'),
    path('delete_user_report/<pk>/', views.delete_user_report, name='delete_user_report'),
]

main/urls.py
from django.urls import path
from . import views  # Import the views from the same directory

urlpatterns = list({
    path('', views.home, name='home'),  # Home page (index.html)
    path('register/', views.register, name='register'),  # Register page (register.html)
    path('contact/', views.contact, name='contact'),  # Contact page
    path('login/', views.login_view, name='login'),
})

newsfeed/urls.py
from django.urls import path, re_path
from Marketplace_webpage.views import home
from custom_admin.views import user_reports
from newsfeed.views import newsfeed, post_product, profile, edit_profile, logout_view, delete_listing, \
    category_selection, electronics, fashion, garden, sports, edit_listing, report_listing, report_user, search, \
    listing_detail

app_name = 'newsfeed'

urlpatterns = [
    path('', newsfeed, name='newsfeed'),
    path('logout/', logout_view, name='logout'),
    path('post/', post_product, name='post_product'),
    path('profile/', profile, name='profile'),
    path('profile/<pk>/', profile, name='profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('delete-listing/<pk>/', delete_listing, name='delete_listing'),
    path('edit_listing/<pk>/', edit_listing, name='edit_listing'),
    path('report_listing/<pk>/', report_listing, name='report_listing'),
    path('listing/<pk>/', listing_detail, name='listing_detail'),
    path('report_user/<pk>/', report_user, name='report_user'),
    path('categories/', category_selection, name='category_selection'),
    path('search/', search, name='search'),
    path('electronics/', electronics, name='electronics'),
    path('fashion/', fashion, name='fashion'),
    path('garden/', garden, name='garden'),
    path('sports/', sports, name='sports'),
    path('user_reports/', user_reports, name='user_reports'),
]

newsfeed/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model


User = get_user_model()



from django.db import models
from django.utils import timezone

class Product(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/')
    mobile_number = models.CharField(max_length=20)
    location = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=50, choices=[('Electronics', 'Electronics'), ('Fashion and Beauty', 'Fashion and Beauty'), ('Home and Garden', 'Home and Garden'), ('Sports and Leisure', 'Sports and Leisure'), ('Others', 'Others')], default='Others')
    is_active = models.BooleanField(default=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.deleted_at = timezone.now()
        self.save()

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images')

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile_number = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    profile_picture = models.ImageField(upload_to='profile_pictures', blank=True, null=True)

    def __str__(self):
        return self.user.username

def profile_view(request, pk):
    user = get_object_or_404(User, pk=pk)
    return render(request, 'profile.html', {'user': user})

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

from django.db import models
from django.contrib.auth.models import User

class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rated_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rated_user')
    rating = models.IntegerField()
    comment = models.TextField(blank=True)

    def __str__(self):
        return f'{self.user.username} rated {self.rated_user.username} {self.rating}/5'

class Report(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reason = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Listing Report'
        verbose_name_plural = 'Listing Reports'

    def __str__(self):
        return f"{self.product.title} listing reported by {self.user.username}"

class UserReport(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reported_user')
    reported_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reporter')
    reason = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} reported by {self.reported_by.username}"

newsfeed/views.py
from custom_admin.views import is_staff
from .models import Product, User, UserReport, ProductImage
from .forms import PostProductForm
from django.contrib import messages
from .forms import ProfileForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Profile, Product, Report
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Rating
from .forms import ProfileForm, RatingForm
from django.db.models import Avg, Count
from django.utils import timezone


def logout_view(request):
    logout(request)
    return redirect('index', logout=True)


from django.utils import timezone
from django.contrib.auth.decorators import login_required


@login_required
def newsfeed(request):
    # Filter out products that are inactive or have been deleted
    products = Product.objects.filter(is_active=True, deleted_at__isnull=True).order_by('-created_at')

    # Convert created_at to local time for each product
    for product in products:
        product.created_at = timezone.localtime(product.created_at)

    return render(request, 'newsfeed.html', {'products': products})

def listing_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    return render(request, 'listing_detail.html', {'product': product})

def post_product(request):
    if request.method == 'POST':
        form = PostProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.category = form.cleaned_data['category']
            product.save()
            # Save multiple images
            for file in request.FILES.getlist('image'):
                ProductImage.objects.create(product=product, image=file)
            messages.success(request, 'Your product has been successfully listed!')
            return redirect('newsfeed:newsfeed')
    else:
        form = PostProductForm()
    return render(request, 'post_product.html', {'form': form})


@login_required
def profile(request, pk):
    if pk is None:
        pk = request.user.pk
    user = get_object_or_404(User, pk=pk)
    profile = user.profile
    is_owner = user == request.user

    # Move the ratings query to the top
    ratings = Rating.objects.filter(rated_user=user)

    # Calculate the summary ratings
    average_rating, star_equivalent_average_rating, num_ratings = get_rating_summary(ratings)

    if request.method == 'POST':
        if is_owner:
            edit_form = ProfileForm(request.POST, instance=profile)
            if edit_form.is_valid():
                edit_form.save()
                messages.success(request, 'Profile updated successfully!')
                return redirect('newsfeed:newsfeed')
        else:
            rating_form = RatingForm(request.POST)
            if rating_form.is_valid():
                rating = rating_form.save(commit=False)
                rating.user = request.user
                rating.rated_user = user
                rating.save()
                messages.success(request, 'Your review has been submitted successfully!')
                # Refresh the ratings query to include the newly submitted rating
                ratings = Rating.objects.filter(rated_user=user)
                # Recalculate the summary ratings
                average_rating, star_equivalent_average_rating, num_ratings = get_rating_summary(ratings)

    if is_owner:
        edit_form = ProfileForm(instance=profile)
        rating_form = None
    else:
        edit_form = None
        rating_form = RatingForm()

    products = Product.objects.filter(user=user, deleted_at__isnull=True)

    # Pass ratings and summary ratings to the template context in all cases
    return render(request, 'profile.html',
                  {'products': products, 'edit_form': edit_form, 'rating_form': rating_form, 'user': user,
                   'is_owner': is_owner, 'ratings': ratings, 'average_rating': average_rating,
                   'star_equivalent_average_rating': star_equivalent_average_rating, 'num_ratings': num_ratings})

def get_rating_summary(ratings):
    if ratings:
        average_rating = sum(rating.rating for rating in ratings) / len(ratings)
        if average_rating is not None:
            star_equivalent_average_rating = round(average_rating, 1)  # assuming 1 decimal place
        else:
            star_equivalent_average_rating = None
        num_ratings = len(ratings)
    else:
        average_rating = None
        star_equivalent_average_rating = None
        num_ratings = 0
    return average_rating, star_equivalent_average_rating, num_ratings

@login_required
def delete_listing(request, pk):
    listing = get_object_or_404(Product, pk=pk)
    if listing.user == request.user:
        listing.deleted_at = timezone.now()
        listing.save()
        messages.success(request, 'Listing deleted successfully!')
        return redirect('newsfeed:profile', pk=request.user.pk)
    else:
        messages.error(request, 'You do not have permission to delete this listing.')
        return redirect('newsfeed:profile', pk=request.user.pk)
@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully!')
            return redirect('newsfeed:newsfeed')
    else:
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'edit_profile.html', {'form': form})

@login_required
def edit_listing(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if product.user == request.user:
        if request.method == 'POST':
            form = PostProductForm(request.POST, request.FILES, instance=product)
            if form.is_valid():
                form.save()
                messages.success(request, 'Listing updated successfully!')
                return redirect('newsfeed:newsfeed')
        else:
            form = PostProductForm(instance=product)
        return render(request, 'edit_listing.html', {'form': form})
    else:
        messages.error(request, 'You do not have permission to edit this listing.')
        return redirect('newsfeed:newsfeed')

@login_required
def report_listing(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if product.user == request.user:
        messages.error(request, 'You cannot report your own listing.')
        return redirect('newsfeed:newsfeed')
    if request.method == 'POST':
        reason = request.POST.get('reason')
        report = Report.objects.create(product=product, user=request.user, reason=reason)
        messages.success(request, 'Listing reported successfully!')
        return redirect('newsfeed:newsfeed')
    return render(request, 'report_listing.html')

@login_required
def report_user(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        reason = request.POST.get('reason')
        report = UserReport.objects.create(user=user, reported_by=request.user, reason=reason)
        messages.success(request, 'User  reported successfully!')
        return redirect('newsfeed:newsfeed')
    return render(request, 'report_user.html')

def category_selection(request):
    return render(request, 'category_selection.html')

def search(request):
    if request.method == 'GET':
        query = request.GET.get('q')
        if query:
            users = User.objects.filter(username__icontains=query, is_superuser=False)  # Exclude superusers
            products = Product.objects.filter(title__icontains=query) | Product.objects.filter(description__icontains=query)
            products = products.filter(is_active=True, deleted_at__isnull=True).order_by('-created_at')
            for product in products:
                product.created_at = timezone.localtime(product.created_at)
            return render(request, 'search_results.html', {'query': query, 'users': users, 'products': products})
    return redirect('newsfeed:newsfeed')

from django.shortcuts import render
from .models import Product

def electronics(request):
    products = Product.objects.filter(category='Electronics', is_active=True, deleted_at__isnull=True)
    for product in products:
        product.created_at = timezone.localtime(product.created_at)
    return render(request, 'electronics.html', {'products': products})

def fashion(request):
    products = Product.objects.filter(category='Fashion and Beauty', is_active=True, deleted_at__isnull=True)
    for product in products:
        product.created_at = timezone.localtime(product.created_at)
    return render(request, 'fashion.html', {'products': products})

def garden(request):
    products = Product.objects.filter(category='Home and Garden', is_active=True, deleted_at__isnull=True)
    for product in products:
        product.created_at = timezone.localtime(product.created_at)
    return render(request, 'garden.html', {'products': products})

def sports(request):
    products = Product.objects.filter(category='Sports and Leisure', is_active=True, deleted_at__isnull=True)
    for product in products:
        product.created_at = timezone.localtime(product.created_at)
    return render(request, 'sports.html', {'products': products})

@login_required
@user_passes_test(is_staff)
def user_reports(request):
    reports = UserReport.objects.all()
    return render(request, 'user_reports.html', {'reports': reports})

newsfeed/templates/edit_listing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Listing - Marketplace</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        .container {
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-bottom: none; /* Remove border bottom */
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 10px;
        }

        .form-group input, .form-group textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .form-group textarea {
            height: 100px;
        }

        .button {
            background-color:  #2196F3;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .button:hover {
            background-color: #3e8e41;
        }

        body {
            margin: 0;
            padding: 0;
            padding-bottom: 50px; /* Add padding to the bottom of the body */
        }
        .error-message {
    color: red;
    border: 1px solid red;
    padding: 5px;
    background-color: #ffcccc;
}

        footer {
            background-color: ;
            padding: 10px;
            text-align: center;
            width: 100%;
        }
        .post-product-box {
  background-color: #fff;
  padding: 20px;
  border: 1px solid #ccc;
  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  margin-bottom: 20px;
  text-align: center;
}

.post-product-box h2 {
  margin-top: 0;
  text-align: left;
}

.product-info .form-group {
  margin-bottom: 20px;
  display: inline-block;
  text-align: left;
  width: 80%;
  margin: 0 auto;
}

.product-info label {
  display: block;
  margin-bottom: 10px;
}

.product-info input, .product-info textarea {
  width: 100%;
  padding: 10px;
  margin-bottom: 20px;
  border: 1px solid #ccc;
  border-radius: 5px;
}

.product-info textarea {
  height: 100px;
}

.button-group {
  padding: 20px;
  border-top: 1px solid #ddd;
  text-align: center;
}

.button-group .button {
  background-color: #2196F3;
  color: #fff;
  padding: 10px 20px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

.button-group .button:hover {
  background-color: #3e8e41;
}
header {
            background-image: url("{% static 'main/8422166.jpg' %}");
            background-size: cover;
            background-position: center;
            height: 100px;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
        footer {
            background-image: url("{% static 'main/8422166.jpg' %}");
            background-size: cover;
            background-position: center;
            height: 50px;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1 class="logo">Ecalp Techmar</h1>
            <nav>
                <ul>
                    <li><a href="{% url 'newsfeed:newsfeed' %}"><i class="fas fa-home"></i> News Feed</a></li>
                                        <li><a href="{% url 'newsfeed:profile' request.user.pk %}"><i class="fas fa-user"></i> Profile</a></li>

                </ul>
            </nav>
        </div>
    </header>

<section id="edit-listing">
    <div class="container">
        <h2>Edit Listing</h2>
        <div class="post-product-box">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Title:</label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    <label for="id_description">Description:</label>
                    {{ form.description }}
                </div>
                <div class="form-group">
                    <label for="id_price">Price:</label>
                    {{ form.price }}
                </div>
                <div class="form-group">
                    <label for="id_mobile_number">Mobile Number (+63)</label>
                    {% if form.mobile_number.errors %}
                        <div class="error-message">
                            {{ form.mobile_number }}
                            <span>{{ form.mobile_number.errors }}</span>
                        </div>
                    {% else %}
                        {{ form.mobile_number }}
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="id_location">Location:</label>
                    {{ form.location }}
                </div>
                <div class="form-group">
                    <label for="id_category">Category:</label>
                    {{ form.category }}
                </div>
                <button type="submit" class="update-button" style="background-color: green; color: white;"><i class="fas fa-save"></i> Update</button>
            </form>
        </div>
    </div>
</section>
    <footer>
        <div class="container">
            <div class="footer-content">
                <p style="text-align: center; width: 100%;">&copy; 2024 Ecalp Techmar. All rights reserved.</p>
            </div>
        </div>
    </footer>
</body>
</html>

newsfeed/templates/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile - Marketplace</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        .container {
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        header {
            background-image: url("{% static 'main/8422166.jpg' %}");
            background-size: cover;
            background-position: center;
            height: 200px;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
        footer {
            background-image: url("{% static 'main/8422166.jpg' %}");
            background-size: cover;
            background-position: center;
            height: 85px;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
        .report-form {
    max-width: 500px;
    margin: 20px auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

.form-group {
    margin-bottom: 20px;
}

.form-label {
    display: block;
    margin-bottom: 10px;
}

.form-control {
    width: 100%;
    padding: 10px;
    margin-bottom: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    resize: none;
}

.report-button {
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: #dc3545;
    color: #fff;
    border: none;
    padding: 10px 20px;
    border-radius: 5px;
    cursor: pointer;
    margin: 0 auto;
    font-weight: bold;
}

.report-button:hover {
    background-color: #c82333;
}

.report-button i {
    margin-right: 5px;
    color: #fff;
}
footer {
  position: fixed;
  bottom: 0;
  width: 100%;
  background-color: #ccc; /* change to your desired color */
  padding: 10px;
  text-align: center;
}
    </style>
</head>
<body>
    <!-- rest of the HTML structure -->
    <header>
        <div class="container">
            <h1 class="logo">Ecalp Techmar</h1>
            <nav>
                <ul>
                    <li><a href="{% url 'newsfeed:newsfeed' %}"><i class="fas fa-home"></i> News Feed</a></li>
                    <li><a href="{% url 'newsfeed:profile' request.user.pk %}"><i class="fas fa-user"></i> Profile</a></li>

        </div>
    </header>
    <section id="edit-profile">
    <div class="container">
        <h2>Edit Profile</h2>
        <form method="post" class="report-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="report-button" style="background-color: green; color: white;"><i class="fas fa-save"></i> Save Changes</button>
</form>
    </div>
</section>
    <footer>
        <div class="container">
            <div class="footer-content">
                <p style="text-align: center; width: 100%;">&copy; 2024 Ecalp Techmar. All rights reserved.</p>
            </div>
        </div>
    </footer>
</body>
</html>

newsfeed/templates/post_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post a Product Listing - Marketplace</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>

.product-info p {
  font-size: 16px;
  margin-bottom: 10px;
}

.button-group .button {
  background-color: #2196F3;
  color: #fff;
  padding: 10px 20px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

.button-group .button:hover {
  background-color: #3e8e41;
}

        .container {
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-bottom: none; /* Remove border bottom */
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 10px;
        }

        .form-group input, .form-group textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .form-group textarea {
            height: 100px;
        }

        .button {
            background-color:  #2196F3;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .button:hover {
            background-color: #3e8e41;
        }

        body {
            margin: 0;
            padding: 0;
            padding-bottom: 50px; /* Add padding to the bottom of the body */
        }
        .error-message {
    color: red;
    border: 1px solid red;
    padding: 5px;
    background-color: #ffcccc;
}

        footer {
            background-color: ;
            padding: 10px;
            text-align: center;
            width: 100%;
        }
        .post-product-box {
  background-color: #fff;
  padding: 20px;
  border: 1px solid #ccc;
  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  margin-bottom: 20px;
  text-align: center;
}

.post-product-box h2 {
  margin-top: 0;
  text-align: left;
}

.product-info .form-group {
  margin-bottom: 20px;
  display: inline-block;
  text-align: left;
  width: 80%;
  margin: 0 auto;
}

.product-info label {
  display: block;
  margin-bottom: 10px;
}

.product-info input, .product-info textarea {
  width: 100%;
  padding: 10px;
  margin-bottom: 20px;
  border: 1px solid #ccc;
  border-radius: 5px;
}

.product-info textarea {
  height: 100px;
}

.button-group {
  padding: 20px;
  border-top: 1px solid #ddd;
  text-align: center;
}

.button-group .button {
  background-color: #2196F3;
  color: #fff;
  padding: 10px 20px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

.button-group .button:hover {
  background-color: #3e8e41;
}
header {
            background-image: url("{% static 'main/8422166.jpg' %}");
            background-size: cover;
            background-position: center;
            height: 100px;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
        footer {
            background-image: url("{% static 'main/8422166.jpg' %}");
            background-size: cover;
            background-position: center;
            height: 50px;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1 class="logo">Ecalp Techmar</h1>
            <nav>
                <ul>
                    <li><a href="{% url 'newsfeed:newsfeed' %}"><i class="fas fa-home"></i> News Feed</a></li>
                </ul>
            </nav>
        </div>
    </header>

<section id="post-product">
    <div class="container">
        <h2>Post a Product Listing</h2>
        <div class="post-product-box">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Title:</label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    <label for="id_description">Description:</label>
                    {{ form.description }}
                </div>
                <div class="form-group">
                    <label for="id_price">Price:</label>
                    {{ form.price }}
                </div>
                <div class="form-group">
    <label for="id_image">Images:</label>
    {{ form.image }}
    <small class="text-muted">You can upload multiple images.</small>
</div>
                <div class="form-group">
                    <label for="id_mobile_number">Mobile Number (+63)</label>
                    {% if form.mobile_number.errors %}
                        <div class="error-message">
                            {{ form.mobile_number }}
                            <span>{{ form.mobile_number.errors }}</span>
                        </div>
                    {% else %}
                        {{ form.mobile_number }}
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="id_location">Location:</label>
                    {{ form.location }}
                </div>
                <div class="form-group">
                    <label for="id_category">Category:</label>
                    {{ form.category }}
                </div>
                <button type="submit" class="button">Post</button>
            </form>
        </div>
    </div>
</section>
    <footer>
        <div class="container">
            <div class="footer-content">
                <p style="text-align: center; width: 100%;">&copy; 2024 Ecalp Techmar. All rights reserved.</p>
            </div>
        </div>
    </footer>
</body>
</html>